version: "3.8"

services: 
    web-platform:
        build:
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./src:/src
        command: sh -c "python manage.py wait_for_db &&
                        python manage.py runserver 0.0.0.0:8000 --settings=settings.local"
        env_file: .env
        depends_on: 
            - db
    pgadmin:
        image: dpage/pgadmin4
        ports: 
            - "5050:5050"
        depends_on:
            - db
        env_file:
            - .env


    db:
        image: postgres:13-alpine
        env_file: .env
        volumes: 
            - pgdata:/var/lib/postgresql/data
    
    redis_db:
        image: redis:5

volumes: 
    pgdata:

