version: "3.8"

services: 
    web-platform:
        build:
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./src:/src
        command: sh -c "python manage.py wait_for_db --settings=settings.local &&
                        python manage.py runserver 0.0.0.0:8000 --settings=settings.local"
        # env_file: ./src/.env
    
    # redis_db:
    #     image: redis:5

